spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db
    username: root
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: prod